# Generated by Django 6.0.3 on 2026-05-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='gst_percentage',
            field=models.FloatField(default=0),
        ),
    ]
