# Generated by Django 6.0.3 on 2026-05-12 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_item_gst_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expiring_date',
            new_name='Purchase_date',
        ),
    ]
