# Generated by Django 6.0.3 on 2026-05-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_expiring_date_item_purchase_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Purchase_date',
            new_name='purchase_date',
        ),
    ]
