# Generated by Django 6.0.3 on 2026-05-25 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor_email_vendor_gst_number_alter_vendor_address'),
        ('store', '0004_rename_purchase_date_item_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor'),
        ),
    ]
