# Generated by Django 5.1 on 2026-06-06 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_cust_co_first_name_idx_and_more'),
        ('companies', '0002_seed_default_company'),
        ('store', '0006_multi_company_saas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['company', 'quantity'], name='item_company_quantity_idx'),
        ),
    ]
