# Generated by Django 5.1 on 2026-07-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_multi_company_saas'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HSN Code'),
        ),
    ]
