# Generated by Django 5.1 on 2026-05-29 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'ordering': ['-date', '-id']},
        ),
    ]
