# Generated by Django 5.1 on 2026-05-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_stabilization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={},
        ),
    ]
