# Generated by Django 5.1 on 2026-06-06 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_multi_company_saas'),
        ('companies', '0002_seed_default_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'first_name'], name='cust_co_first_name_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['company', 'last_name'], name='cust_co_last_name_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company', 'name'], name='vendor_company_name_idx'),
        ),
    ]
