# Generated by Django 6.0.3 on 2026-05-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_purchase_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('WALLET', 'Wallet'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Mode'),
        ),
    ]
