# Generated by Django 6.0.3 on 2026-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_purchase_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
    ]
