# Generated by Django 6.0.3 on 2026-05-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_purchase_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_mode',
            field=models.CharField(choices=[('NONE', 'None'), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20, verbose_name='Payment Mode'),
        ),
    ]
