# Generated by Django 6.0.3 on 2026-05-16 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_purchase_date_item_purchase_date'),
        ('transactions', '0007_alter_purchase_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.PROTECT, to='store.item'),
        ),
    ]
