# Generated by Django 6.0.3 on 2026-05-20 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_purchase_options_remove_purchase_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('NONE', 'None'), ('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('DEBIT_CARD', 'Debit Card'), ('CHEQUE', 'Cheque'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.purchase')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
