# Generated by Django 6.0.3 on 2026-05-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_vendor'),
        ('transactions', '0010_purchasepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(blank=True, db_column='item', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item'),
        ),
    ]
