# Generated by Django 6.0.3 on 2026-05-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_item_vendor'),
        ('transactions', '0011_purchaseitem_item_name_saledetail_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='saledetail',
            name='item_name',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='item',
            field=models.ForeignKey(db_column='item', on_delete=django.db.models.deletion.DO_NOTHING, to='store.item'),
        ),
    ]
