# Generated by Django 5.1 on 2026-05-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_saledetail_gst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-order_date']},
        ),
    ]
