# Generated by Django 5.1 on 2026-05-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Invoice ID'),
        ),
    ]
