# Generated by Django 5.1 on 2026-06-06 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_cust_co_first_name_idx_and_more'),
        ('companies', '0002_seed_default_company'),
        ('transactions', '0018_purchase_invoice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'order_date'], name='purch_co_order_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'delivery_date'], name='purch_co_delivery_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['company', 'date_added'], name='sale_company_date_added_idx'),
        ),
    ]
