# Generated by Django 6.0.3 on 2026-05-03 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_grand_total_and_more'),
        ('store', '0001_initial'),
        ('transactions', '0003_alter_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='transactions.sale'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Grand Total'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='price_per_item',
            field=models.FloatField(default=0.0, verbose_name='Price Per Item'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping',
            field=models.FloatField(default=0.0, verbose_name='Shipping and Handling'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.FloatField(default=0.0, editable=False, verbose_name='Total Amount'),
        ),
    ]
