# Generated by Django 6.0.3 on 2026-05-16 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_invoice_sale_alter_invoice_contact_number_and_more'),
        ('store', '0004_rename_purchase_date_item_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='contact_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('line_total', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoice.invoice')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item')),
            ],
        ),
    ]
