# Generated by Django 5.1 on 2026-05-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_invoice_line_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='price',
            field=models.FloatField(default=0.0, help_text='Unit rate before GST'),
        ),
    ]
